# Generated by Django 5.2.8 on 2026-10-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'name'], name='customers_c_busines_67b0d8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('business', 'phone'), name='unique_customer_phone_per_business_when_present')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'name'], name='customers_s_busines_94d0d8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('business', 'phone'), name='unique_supplier_phone_per_business_when_present')],
            },
        ),
    ]
